# Generated by Django 4.0.4 on 2022-05-24 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_person', models.CharField(max_length=100)),
                ('organization', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('value', models.IntegerField(default=0)),
                ('pipeline', models.CharField(max_length=100)),
                ('pipeline_stage', models.CharField(max_length=100)),
                ('expected_close_date', models.DateField()),
                ('visible_to', models.CharField(max_length=100)),
                ('mobile_no', models.CharField(max_length=100)),
                ('work_mobile_no', models.CharField(max_length=100)),
                ('personal_email', models.CharField(max_length=100)),
                ('work_email', models.CharField(max_length=201000)),
            ],
        ),
    ]
